language: node_js

node_js:
  - "node"

env:
  - NODE_ENV=ci

install:
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - yarn test
  - yarn run lint
  - yarn run build
